Repository awslabs/soci-snapshotter, pull requests merged in 2024-07, with the labels that each got.

#1281 Remove ioutils.CountWriter
  fs/artifact_fetcher.go
  util/ioutils/countwriter.go
Labels: go

#1289 Allow insecure localhost connections
  fs/artifact_fetcher.go
  fs/artifact_fetcher_test.go
Labels: go, testing

#1308 Update deprecated packages
  cmd/go.mod
  cmd/go.sum
  cmd/soci/commands/index/list.go
  cmd/soci/commands/internal/platform.go
  cmd/soci/commands/ztoc/list.go
  go.mod
  go.sum
  integration/create_test.go
  integration/index_test.go
  integration/pull_test.go
  integration/push_test.go
  integration/util_soci_test.go
  integration/util_test.go
  service/keychain/cri/v1/cri.go
  service/keychain/cri/v1alpha/cri.go
  service/plugin/plugin.go
  soci/artifacts.go
  soci/soci_index.go
Labels: dependencies, go, testing

#1309 Test against containerd 2.0 in CI
  .github/workflows/build.yml
Labels: github_actions

#1311 Use rabbitmqImage in FUSE failure test
  integration/metrics_test.go
Labels: go, testing

#1312 Add back containerd 2.0 testing to CI
  .github/workflows/build.yml
Labels: github_actions

#1315 Revert "Disable xattrs by default"
  cmd/soci/commands/create.go
  config/config.toml
  docs/cli-usage.md
  soci/soci_index.go
  soci/soci_index_test.go
Labels: go, testing

#1318 Bump containerd 1.6 and 1.7 versions to latest
  .github/workflows/build.yml
  Dockerfile
Labels: github_actions

#1302 Fallback to containerd if we are unable to fetch SOCI artifacts
  fs/fs.go
  integration/metrics_test.go
  snapshot/snapshot.go
Labels: go, testing

#1233 Add integration test for offline content
  integration/run_test.go
Labels: go, testing

#1322 Update getting started version
  docs/getting-started.md
Labels: documentation

#1327 Add mention of OCI 1.1 in ECR
  docs/registry.md
Labels: documentation
