Repository awslabs/soci-snapshotter, pull requests merged in 2025-08, with the labels that each got.

#1660 Update dependabot.yml and remove custom workflow
  .github/dependabot.yml
  .github/workflows/bump-deps.yml
  scripts/bump-deps.sh
Labels: github_actions

#1666 Use -q flag when pulling with nerdctl in tests
  integration/convert_test.go
  integration/create_test.go
  integration/pull_modes_test.go
  integration/util_test.go
Labels: go, testing

#1672 Migrate soci to urfave/cli/v2
  cmd/go.mod
  cmd/go.sum
  cmd/soci-snapshotter-grpc/main.go
  cmd/soci/commands/convert.go
  cmd/soci/commands/create.go
  cmd/soci/commands/index/index.go
  cmd/soci/commands/index/info.go
  cmd/soci/commands/index/list.go
  cmd/soci/commands/index/rm.go
  cmd/soci/commands/internal/client.go
  cmd/soci/commands/internal/index.go
  cmd/soci/commands/internal/label.go
  cmd/soci/commands/internal/platform.go
  cmd/soci/commands/internal/registry.go
  cmd/soci/commands/internal/snapshotter.go
  cmd/soci/commands/internal/store.go
  cmd/soci/commands/push.go
  cmd/soci/commands/rebuild_db.go
  cmd/soci/commands/ztoc/get-file.go
  cmd/soci/commands/ztoc/info.go
  cmd/soci/commands/ztoc/list.go
  cmd/soci/commands/ztoc/ztoc.go
  cmd/soci/main.go
  integration/push_test.go
  integration/util_soci_test.go
Labels: dependencies, go, testing

#1674 Revert "Update dependabot.yml and remove custom workflow"
  .github/dependabot.yml
  .github/workflows/bump-deps.yml
  scripts/bump-deps.sh
Labels: github_actions

#1675 Remove filenames from `metadata` error logs
  metadata/db.go
  metadata/reader.go
Labels: go

#1688 Use DirectMountStrict if fusermount is missing
  fs/fs.go
Labels: go

#1676 Migrate soci command to urfave/cli/v3
  cmd/go.mod
  cmd/go.sum
  cmd/soci-snapshotter-grpc/main.go
  cmd/soci/commands/convert.go
  cmd/soci/commands/create.go
  cmd/soci/commands/index/index.go
  cmd/soci/commands/index/info.go
  cmd/soci/commands/index/list.go
  cmd/soci/commands/index/rm.go
  cmd/soci/commands/internal/client.go
  cmd/soci/commands/internal/index.go
  cmd/soci/commands/internal/label.go
  cmd/soci/commands/internal/platform.go
  cmd/soci/commands/internal/registry.go
  cmd/soci/commands/internal/snapshotter.go
  cmd/soci/commands/internal/store.go
  cmd/soci/commands/push.go
  cmd/soci/commands/rebuild_db.go
  cmd/soci/commands/ztoc/get-file.go
  cmd/soci/commands/ztoc/info.go
  cmd/soci/commands/ztoc/list.go
  cmd/soci/commands/ztoc/ztoc.go
  cmd/soci/main.go
  integration/create_test.go
Labels: dependencies, go, testing
