Repository awslabs/soci-snapshotter, pull requests merged in 2025-04, with the labels that each got.

#1501 Refactor SOCI Index Build API
  cmd/soci/commands/create.go
  soci/soci_index.go
  soci/soci_index_test.go
Labels: go, testing, API Change

#1493 Remove ORAS Resolve calls in MountLocal
  fs/artifact_fetcher.go
  fs/fs.go
  fs/remote/resolver.go
  fs/remote/resolver_test.go
  service/resolver/cri.go
  service/resolver/registry.go
Labels: go, testing

#1502 Attach SOCI index GC to Image
  cmd/soci/commands/create.go
  integration/create_test.go
  soci/soci_index.go
Labels: go, testing

#1509 Always use namespace from request context
  cmd/soci-snapshotter-grpc/main.go
  cmd/soci-snapshotter-grpc/namespaces.go
  cmd/soci/commands/create.go
  cmd/soci/commands/index/info.go
  cmd/soci/commands/index/rm.go
  cmd/soci/commands/internal/client.go
  cmd/soci/commands/internal/store.go
  cmd/soci/commands/push.go
  cmd/soci/commands/rebuild_db.go
  cmd/soci/commands/ztoc/get-file.go
  cmd/soci/commands/ztoc/info.go
  cmd/soci/commands/ztoc/list.go
  config/fs.go
  fs/fs.go
  fs/source/source.go
  integration/run_test.go
  snapshot/snapshot.go
  soci/artifacts.go
  soci/store/store.go
Labels: go, testing, API Change

#1504 Refactor SOCI Init logic
  fs/fs.go
Labels: go

#1478 Update containerd {1.6.38,1.7.27,2.0.4} in CI
  .github/workflows/build.yml
  Dockerfile
Labels: github_actions

#1515 Disable systemd tests on x86 codebuild
  .github/workflows/build.yml
  integration/startup_test.go
Labels: go, testing, github_actions

#1514 Update golang.org/x/net to v0.39.0
  cmd/go.mod
  cmd/go.sum
  go.mod
  go.sum
Labels: dependencies

#1512 Use functional args for config in integ tests
  config/config.toml
  integration/create_test.go
  integration/metrics_test.go
  integration/pull_test.go
  integration/push_test.go
  integration/rebuild-db_test.go
  integration/run_test.go
  integration/startup_test.go
  integration/util_test.go
Labels: go, testing

#1531 Pass cache options to spancache.Get
  fs/span-manager/span_manager.go
Labels: go
