Repository awslabs/soci-snapshotter, pull requests merged in 2025-07, with the labels that each got.

#1626 Add third party licenses file for release v0.10.1.
  docs/eks.md
  docs/getting-started.md
Labels: documentation

#1646 fix: check if commit failed due to content already exists
  soci/store/store.go
Labels: go

#1652 script to setup SOCI parallel pull/unpack mode
  scripts/parallel-mode-install.sh
Labels: github_actions

#1600 Move the snapshotter to urfave
  cmd/soci-snapshotter-grpc/main.go
Labels: go
