Repository awslabs/soci-snapshotter, pull requests merged in 2025-05, with the labels that each got.

#1539 Fix config mediatype in Convert
  integration/convert_test.go
  soci/soci_convert.go
Labels: go, testing

#1518 Consume index annotations
  config/config.go
  config/config_test.go
  config/defaults.go
  config/pull_modes.go
  config/service.go
  fs/fs.go
  integration/pull_modes_test.go
  integration/util_test.go
  service/service.go
  util/testutil/shell.go
Labels: go, testing

#1548 Increase CI Integration test timeout
  .github/workflows/build.yml
Labels: github_actions

#1550 ci: integrate test containerd@v2.1.0-rc.1
  .github/workflows/build.yml
Labels: github_actions

#1551 Add FetchSociArtifacts test
  fs/artifact_fetcher_test.go
Labels: go, testing

#1559 docs: add containerd 2.0+ configuration details for k8s
  docs/kubernetes.md
Labels: documentation

#1554 ci: update containerd@v2.1.0 integration testing
  .github/workflows/build.yml
Labels: github_actions

#1563 Add SOCI CLI root flag
  cmd/soci-snapshotter-grpc/main.go
  cmd/soci/commands/convert.go
  cmd/soci/commands/create.go
  cmd/soci/commands/index/info.go
  cmd/soci/commands/index/list.go
  cmd/soci/commands/index/rm.go
  cmd/soci/commands/push.go
  cmd/soci/commands/rebuild_db.go
  cmd/soci/commands/ztoc/get-file.go
  cmd/soci/commands/ztoc/info.go
  cmd/soci/commands/ztoc/list.go
  cmd/soci/main.go
  config/config.go
  soci/artifacts.go
  soci/artifacts_test.go
  soci/fs.go
  soci/fs_test.go
  soci/soci_index.go
Labels: go, testing

#1547 Test invalid conversions
  integration/convert_test.go
  integration/util_test.go
Labels: go, testing

#1568 Add test for span arg validation
  integration/create_test.go
  soci/soci_index.go
Labels: go, testing

#1571 Resolve descriptor before unpacking
  fs/fs.go
Labels: go
