Repository awslabs/soci-snapshotter, pull requests merged in 2025-03, with the labels that each got.

#1480 Add Go 1.23 branch to build/prebuild workflows
  .github/workflows/build.yml
  .github/workflows/prebuild.yml
Labels: github_actions

#1481 Properly refresh expired tokens
  service/resolver/client.go
Labels: go

#1483 Bump golang.org/x/net from 0.33.0 to 0.37.0
  cmd/go.mod
  cmd/go.sum
  go.mod
  go.sum
Labels: dependencies

#1482 fix: fuse file seek
  cmd/go.mod
  cmd/go.sum
  go.mod
  go.sum
Labels: dependencies

#1485 Bump golang.org/x/oauth2 from 0.21.0 to 0.28.0
  cmd/go.mod
  cmd/go.sum
  go.mod
  go.sum
Labels: dependencies

#1494 Add metric for failing to prepare local snapshot
  fs/metrics/common/metrics.go
  snapshot/snapshot.go
Labels: go
